apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-loaq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-loaq
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-loaq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-loaq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-loaq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jtbw-tenant/rhtap-demo-app/hacbs-test-project-loaq@sha256:f5ad0e43f8348c54b726c3f25f5e071f015540efda94c858de9fd211f7467a9e
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
