apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-loaq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jtbw-tenant/rhtap-demo-app/hacbs-test-project-loaq@sha256:f5ad0e43f8348c54b726c3f25f5e071f015540efda94c858de9fd211f7467a9e
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
